spring.application.name=goldenhosewarehouse
server.port=8080
# Connection
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=acme_productions

# The Fix for the "Enum" error
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS

# Timeouts
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s

