spring.application.name=goldenetl
server.port=8082
#  (Warehouse DAL)
warehouse.url=http://localhost:8080/api/warehouse/ingest

#Message Broker Configuration
etl.queue.name=nasdaqqueue
# RabbitMQ Connection Settings
# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.amqp.deserialization.trust.all=true
