spring.application.name=producer
server.port=8081

# PROJECT REQ: No hard-coded API Keys
nasdaq.api.key=KQFucboyeT_hwC26GyS5


etl.queue.name=nasdaqqueue

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
